name: Daily Newsletter Delivery

on:
  schedule:
    # Run at 7:00 AM Sao Paulo time (10:00 UTC)
    # Cron syntax: minute hour day-of-month month day-of-week
    - cron: "0 10 * * *"

  # Allow manual triggering
  workflow_dispatch:

jobs:
  send-newsletter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Install dependencies
        run: go mod tidy

      - name: Send newsletter
        env:
          API_KEY: ${{ secrets.RESEND_API_KEY }}
        run: go run main.go send
